on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - name: Install
      run: |
        yes '' | sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt update
        sudo apt install emacs25-nox
        echo `dpkg -L emacs25-nox`
        emacs25 --version
    - name: Test
      run: |
        emacs25 --batch --eval "(progn (add-to-list 'load-path \"$PWD\") (require 'doctest) (doctest \"doctest.el\"))" | grep '0 failed'
