on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          # Add more lines like this if you want to test on different Emacs versions.
          - 27.2

    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Test
      run: |
        emacs25 --batch --eval "(progn (add-to-list 'load-path \"$PWD\") (require 'doctest) (doctest \"doctest.el\"))" | grep '0 failed'
